{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aeos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aeos.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if $.Values.ingress.tls.certArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ $.Values.ingress.tls.certArn }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "aeos.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
