"""
app/certification/report.py

Emit certification run results in two forms:

  * structured JSON   — the machine-readable record (``TierRunResult.to_dict``),
    written verbatim so downstream tooling gets every raw sample stat and the
    full gating decision.
  * human-readable MD  — a certification report a person can read, with the
    environment, the certified/not-certified verdict up top, the disclaimer, and
    a table per measurement dimension.

Both forms carry the same honesty framing: a run that is not a certification
says so in the title, the verdict line, and the disclaimer.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .runner import TierRunResult


def write_json(result: TierRunResult, output_dir: str | Path) -> Path:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{result.run_id}.json"
    path.write_text(json.dumps(result.to_dict(), indent=2), encoding="utf-8")
    return path


def _fmt_stats(m: dict[str, Any]) -> str:
    s = m.get("stats", {})
    if not s:
        return "no samples"
    return (f"min {s['min']} · p50 {s['p50']} · p95 {s['p95']} · "
            f"p99 {s['p99']} · max {s['max']} (n={m['sample_count']})")


def render_markdown(result: TierRunResult) -> str:
    d = result.to_dict()
    env = d["environment"]
    verdict = "✅ CERTIFIED" if d["certified"] else "❌ NOT CERTIFIED"
    title_kind = "Certification" if d["certified"] else "Operational Validation (dev-scale)"

    lines: list[str] = []
    lines.append(f"# AEOS {result.tier.value.title()} {title_kind}")
    lines.append("")
    lines.append(f"**Verdict:** {verdict}  ")
    lines.append(f"**Run ID:** `{d['run_id']}`  ")
    lines.append(f"**Scale profile:** {d['scale_profile']} "
                 f"({'full-scale' if d['scale_is_full'] else 'dev-scale subset'})  ")
    lines.append(f"**Duration:** {d['duration_seconds']}s  ")
    lines.append("")
    lines.append(f"> {d['disclaimer']}")
    lines.append("")

    # Environment
    lines.append("## Environment")
    lines.append("")
    lines.append(f"- **Class:** `{env['environment_class']}`")
    lines.append(f"- **Host:** {env['hostname']} — {env['platform']}")
    lines.append(f"- **Python:** {env['python_version']}, "
                 f"**CPUs:** {env['cpu_count']}, "
                 f"**RAM:** {env['total_memory_mb']} MB")
    lines.append(f"- **Container:** {env['in_container']}, "
                 f"**Kubernetes:** {env['in_kubernetes']}, **CI:** {env['is_ci']}")
    lines.append(f"- **Signals:** {'; '.join(env['classification_signals'])}")
    lines.append("")

    # Verdict detail
    lines.append("## Verdict detail")
    lines.append("")
    lines.append(f"- **Thresholds met at this scale:** "
                 f"{'yes' if d['thresholds_met'] else 'no'}")
    if d["threshold_failures"]:
        for f in d["threshold_failures"]:
            lines.append(f"  - ⚠️ {f}")
    if d["certified_blocked_reasons"]:
        lines.append("- **Why not certified:**")
        for r in d["certified_blocked_reasons"]:
            lines.append(f"  - {r}")
    lines.append("")

    # Measurements
    lines.append("## Measurements (real operations)")
    lines.append("")
    lines.append("| Dimension | Unit | Result | Errors | Notes |")
    lines.append("|-----------|------|--------|--------|-------|")
    for name, m in d["measurements"].items():
        scalar = m.get("scalar", {})
        if name == "throughput_latency":
            headline = (f"{scalar.get('throughput_tps', 0):.1f} tps · "
                        f"latency {_fmt_stats(m)}")
        else:
            headline = _fmt_stats(m)
        note = m["notes"][0] if m.get("notes") else ""
        lines.append(f"| {name} | {m['unit']} | {headline} | "
                     f"{m['error_count']}/{m['total_count']} | {note} |")
    lines.append("")

    lines.append("## Reproduction")
    lines.append("")
    lines.append("```bash")
    lines.append(f"python scripts/certify.py {result.tier.value}")
    lines.append("# On production infra, add --allow-full-scale to attempt a real certification:")
    lines.append(f"python scripts/certify.py {result.tier.value} --allow-full-scale")
    lines.append("```")
    lines.append("")
    lines.append("_Generated by the AEOS certification harness "
                 "(`app/certification`). All numbers are wall-clock measurements "
                 "of real AEOS operations; none are simulated._")
    lines.append("")
    return "\n".join(lines)


def write_markdown(result: TierRunResult, output_dir: str | Path) -> Path:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{result.run_id}.md"
    path.write_text(render_markdown(result), encoding="utf-8")
    return path
