"""
Software Intelligence Platform — Exception Hierarchy
=====================================================
All platform exceptions derive from SoftwareIntelligenceError.
Callers catch at the appropriate level — never catch Exception directly.
"""

from __future__ import annotations


class SoftwareIntelligenceError(Exception):
    """Base exception for the entire OSIP platform."""


# ── Repository ─────────────────────────────────────────────────────────────────
class RepositoryError(SoftwareIntelligenceError): ...
class RepositoryNotFoundError(RepositoryError): ...
class RepositoryAccessError(RepositoryError): ...
class RepositorySyncError(RepositoryError): ...
class RepositoryTooLargeError(RepositoryError): ...


# ── Parsing ────────────────────────────────────────────────────────────────────
class ParseError(SoftwareIntelligenceError): ...
class UnsupportedLanguageError(ParseError): ...
class SyntaxAnalysisError(ParseError): ...


# ── Dependency ─────────────────────────────────────────────────────────────────
class DependencyError(SoftwareIntelligenceError): ...
class CircularDependencyError(DependencyError): ...


# ── Analysis ───────────────────────────────────────────────────────────────────
class AnalysisError(SoftwareIntelligenceError): ...
class SecurityScanError(AnalysisError): ...
class MetricsError(AnalysisError): ...
class ReviewError(AnalysisError): ...


# ── Knowledge Graph ────────────────────────────────────────────────────────────
class KnowledgeGraphError(SoftwareIntelligenceError): ...
class GraphNodeNotFoundError(KnowledgeGraphError): ...


# ── Search ─────────────────────────────────────────────────────────────────────
class SearchError(SoftwareIntelligenceError): ...
class IndexNotReadyError(SearchError): ...


# ── Cache ──────────────────────────────────────────────────────────────────────
class CacheError(SoftwareIntelligenceError): ...
